# Module 4 

## Assignment1

### 1. Create a list named ‘myList’ that has the following elements: 10, 20, 30,‘apple’, True, 8.10:
### a. Now in the ‘myList’, append these values: 30, 40
#### b. After that, reverse the elements of the ‘myList’ and store that in ‘reversedList’


In [2]:
myList = [10, 20, 30, 'apple', True, 8.10]

# a. Append these values: 30, 40
myList.append(30)
myList.append(40)

# b. Reverse the elements of 'myList' and store that in 'reversedList'
reversedList = myList[::-1]

print(myList)
print(reversedList)

[10, 20, 30, 'apple', True, 8.1, 30, 40]
[40, 30, 8.1, True, 'apple', 30, 20, 10]


### 2. Create a dictionary with key values as 1, 2, 3 and the values as ‘data’,‘information’ and ‘text’:
#### a. After that, eliminate the ‘text’ value from the dictionary
#### b. Add ‘features’ in the dictionary
#### c. Fetch the ‘data’ element from the dictionary and display it in the output


In [ ]:
myDict = {1: 'data', 2: 'information', 3: 'text'}

# a. Eliminate the 'text' value from the dictionary
del myDict[3]

# b. Add 'features' in the dictionary
myDict[4] = 'features'

# c. Fetch the 'data' element from the dictionary and display it in the output
data_element = myDict[1]
print(data_element)

### 3. Create a tuple and add these elements 1, 2, 3, apple, mango in my_tuple.


In [3]:
my_tuple = (1, 2, 3, 'apple', 'mango')

### 4. Create another tuple named numeric_tuple consisting of only integer values 10, 20, 30, 40, 50:
##### a. Find the minimum value from the numeric_tuple
##### b. Concatenate my_tuple with numeric_tuple and store the result in r1
##### c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’


In [ ]:
numeric_tuple = (10, 20, 30, 40, 50)

# a. Find the minimum value from the numeric_tuple
min_value = min(numeric_tuple)

# b. Concatenate 'my_tuple' with 'numeric_tuple' and store the result in 'r1'
r1 = my_tuple + numeric_tuple

# c. Duplicate the tuple named 'my_tuple' 2 times and store that in 'newdupli'
newdupli = my_tuple * 2

print(min_value)
print(r1)
print(newdupli)

#### 5. Create 2 sets with the names set1 and set2, where set1 contains
#### {1,2,3,4,5} and set2 contains {2,3,7,6,1}
##### Perform the below operation:
###### a. set1 union set2
###### b. set1 intersection set2
###### c. set1 difference set2

In [1]:
set1 = {1, 2, 3, 4, 5}
set2 = {2, 3, 7, 6, 1}

# a. set1 union set2
union_result = set1.union(set2)

# b. set1 intersection set2
intersection_result = set1.intersection(set2)

# c. set1 difference set2
difference_result = set1.difference(set2)

print(union_result)
print(intersection_result)
print(difference_result)

{1, 2, 3, 4, 5, 6, 7}
{1, 2, 3}
{4, 5}


# Assignment2

### 1.Create a 3x3 matrix array with values ranging from 2 to 10



In [3]:
import numpy as np

In [5]:
arr3_Matrix=np.arange(2,11).reshape(3,3)

In [6]:
arr3_Matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### 2. Create a NumPy array having user input values and convert the integer type to the float type of the elements of the array. For instance: Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]

In [7]:
# Taking user input for array values

user_input = input("Enter values separated by spaces: ")
user_values = [int(x) for x in user_input.split()]

# Creating NumPy array from user input
original_array = np.array(user_values)

# Converting integer type to float type
float_array = original_array.astype(float)

# Displaying the results
print("Original array:", original_array)
print("Array converted to float type:", float_array)


Enter values separated by spaces: 2 2 4 5 6 4 8 9 3 
Original array: [2 2 4 5 6 4 8 9 3]
Array converted to float type: [2. 2. 4. 5. 6. 4. 8. 9. 3.]


### 3. Write a NumPy program to append values to the end of an array. For instance: Original array: [10, 20, 30] . After that, append values to the end of the array: [10 20 30 40 50 60 70 80 90] 

In [9]:
myList = np.array([10, 20, 30])
new_List=np.array([10,20,30,40,50,60,70,80,90])
Append_List=np.append(myList,new_List)
print("Original array:", myList)
print("Append_List:", Append_List)


Original array: [10 20 30]
Append_List: [10 20 30 10 20 30 40 50 60 70 80 90]


### 4. Create two NumPy arrays and add the elements of both the arrays and store the result in sumArray.
 

In [12]:
myarr1 = np.array([10, 20, 30])
myarr2 = np.array([50, 70, 20])
Added_array=myarr1+myarr2
print("Array One:", myarr1)
print("Array Two:", myarr2)
print("Sum of the array:", Added_array)


Array One: [10 20 30]
Array Two: [50 70 20]
Sum of the array: [60 90 50]


### 5. Create a 3x3 array having values from 10-90 (interval of 10) and store that in array1 Perform the following tasks: a. Extract the 1st row from the array b. Extract the last element from the array

In [17]:
arr1=np.arange(10,91,10).reshape(3,3)
print("\nMyArray:")
print(arr1) 

first_row = arr1[0, :]

# b. Extract the last element from the array
last_element = arr1[-1, -1]

# Display the results
print("\nExtracted 1st row:")
print(first_row)

print("\nExtracted last element:")
print(last_element)


MyArray:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Extracted 1st row:
[10 20 30]

Extracted last element:
90
